import { z } from 'zod';

export const metricSchema = z.enum([
  'USERS_OVER_TIME',
  'WORKSPACES_OVER_TIME',
  'TOTAL_USERS',
  'TOTAL_VENUES',
  'USERS_PER_VENUE',
  'VENUES_OVER_TIME',
  'USERS_LIST',
  'VENUES_LIST',
  'TOTAL_VENUES_BY_OWNER',
  'SUPER_PARTICIPANTS_ON_VENUES_BY_OWNER',
  'TOP_3_VENUES_WITH_MOST_MEMBERS',
  'PARTICIPANTS_BY_STATUS_BY_OWNER',
]);
